/*
	
	Copyright (c) 2012, Latitude Geographics Ltd.
	All rights reserved.
	       
	Redistribution is not permitted. 
	
	Use in binary form, without modification, is permitted provided that neither 
	the name of the organization nor the names of its contributors may be used 
	to endorse or promote products derived from this software without specific 
	prior written permission.
	       
	THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY
	EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
	DISCLAIMED. IN NO EVENT SHALL  BE LIABLE FOR ANY
	DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

dojo.provide("geocortex.framework.ui.RegionAdapterBase.js");dojo.provide("geocortex.framework.ui.PopupModalRegionAdapter.js");dojo.provide("geocortex.framework.storage.StorageProviderBase.js");dojo.provide("geocortex.framework.js");dojo.provide("geocortex.framework.application.Application.js");dojo.provide("geocortex.framework.application.ApplicationCommands.js");dojo.provide("geocortex.framework.application.ModuleBase.js");dojo.provide("geocortex.framework.application.ModuleManager.js");dojo.provide("geocortex.framework.application.ResourceManager.js");
dojo.provide("geocortex.framework.commands.Command.js");dojo.provide("geocortex.framework.commands.CommandRegistry.js");dojo.provide("geocortex.framework.config.ConfigurationLoader.js");dojo.provide("geocortex.framework.config.ConfigurationModel.js");dojo.provide("geocortex.framework.config.LibraryConfig.js");dojo.provide("geocortex.framework.config.ModuleConfig.js");dojo.provide("geocortex.framework.config.ViewConfig.js");dojo.provide("geocortex.framework.config.ViewModelConfig.js");dojo.provide("geocortex.framework.events.CollectionChangedArgs.js");
dojo.provide("geocortex.framework.events.Event.js");dojo.provide("geocortex.framework.events.EventRegistry.js");dojo.provide("geocortex.framework.events.Observable.js");dojo.provide("geocortex.framework.events.ObservableCollection.js");dojo.provide("geocortex.framework.events.ViewDimensionsChangedArgs.js");dojo.provide("geocortex.framework.storage.FileStorageProvider.js");dojo.provide("geocortex.framework.storage.LocalStorageProvider.js");dojo.provide("geocortex.framework.storage.StorageStats.js");
dojo.provide("geocortex.framework.storage.Store.js");dojo.provide("geocortex.framework.ui.BindingExpression.js");dojo.provide("geocortex.framework.ui.BindingNode.js");dojo.provide("geocortex.framework.ui.DivRegionAdapter.js");dojo.provide("geocortex.framework.ui.DivStackRegionAdapter.js");dojo.provide("geocortex.framework.ui.MultiDivRegionAdapter.js");dojo.provide("geocortex.framework.ui.ViewBase.js");dojo.provide("geocortex.framework.ui.ViewManager.js");dojo.provide("geocortex.framework.ui.ViewModelBase.js");
dojo.provide("geocortex.framework.utils.Array.js");dojo.provide("geocortex.framework.utils.String.js");dojo.provide("geocortex.framework.utils.ThrottledOperation.js");dojo.provide("geocortex.framework.utils.TimeDelayedAction.js");dojo.provide("geocortex.framework.utils.Trace.js");dojo.provide("geocortex.framework.utils.utils.js");dojo.provide("geocortex.bootstrapper.js");
dojo.declare("geocortex.framework.ui.RegionAdapterBase",null,{constructor:function(a,b){this._activations=0;this._activateViewerTimers=[];this.active=false;this.app=b;this.name=a;this.views=[]},_activations:0,_activateViewerTimers:null,active:null,app:null,domElement:null,name:"",views:null,host:function(a){this.domElement=a},unhost:function(){},activateView:function(a){this._cancelActivate(a);if(this._activations===0&&a.isActive===false)this.isActive=true,this.app.eventRegistry.event("RegionActivatedEvent").publish(this);
a.isActive===false&&++this._activations;a.activated();a.isActive=true;dojo.removeClass(a.root,"inactive");dojo.addClass(a.root,"activating");this._activateViewerTimers[a.id]=setTimeout(dojo.hitch(this,function(){dojo.removeClass(a.root,"activating");dojo.addClass(a.root,"active");delete this._activateViewerTimers[a.id]}),0);this.app.eventRegistry.event("ViewActivatedEvent").publish(a)},_cancelActivate:function(a){this._activateViewerTimers[a.id]&&(clearTimeout(this._activateViewerTimers[a.id]),delete this._activateViewerTimers[a.id],
dojo.removeClass(a.root,"activating"))},deactivateView:function(a){if(this._activations<=1&&a.isActive===true)this.isActive=false,this.app.eventRegistry.event("RegionDeactivatedEvent").publish(this);this._cancelActivate(a);a.isActive===true&&--this._activations;a.deactivated();a.isActive=false;dojo.removeClass(a.root,"active");dojo.addClass(a.root,"inactive");this.app.eventRegistry.event("ViewDeactivatedEvent").publish(a)},hostView:function(a){a.added();dojo.removeClass(a.root,"active");dojo.addClass(a.root,
"inactive");this.app.eventRegistry.event("ViewHostedEvent").publish({region:this,view:a})},unhostView:function(a){a.removed();dojo.removeClass(a.root,"active");dojo.addClass(a.root,"inactive");this.app.eventRegistry.event("ViewUnhostedEvent").publish({region:this,view:a})}});
dojo.declare("geocortex.framework.ui.PopupModalRegionAdapter",geocortex.framework.ui.RegionAdapterBase,{constructor:function(a,b){this.app=b;this.name=a;this.activeViews=[];if(this.app.modalRegionSingleton==null)this.app.modalRegionSingleton=this;this.app.commandRegistry.command("CloseModalRegion").register(this,function(){this.app.modalRegionSingleton.deactivate()});this.app.eventRegistry.event("ViewActivatedEvent").subscribe(this,function(){this.activeViews.length>0&&this.app.modalRegionSingleton.positionContent()});
this.app.eventRegistry.event("ViewDimensionsChangedEvent").subscribe(this,function(){this.app.modalRegionSingleton.positionContent()})},activeView:null,activeViews:null,titleBindingToken:null,contentHeader:null,contentTitle:null,contentContainer:null,contentElement:null,overlayElement:null,_scrollTimer:null,_scrollDelay:50,activate:function(){this.activeViews.length>0&&(dojo.query(this.app.modalRegionSingleton.domElement).removeClass("inactive"),dojo.query(this.app.modalRegionSingleton.domElement).addClass("active"),
dojo.query(this.app.modalRegionSingleton.overlayElement).removeClass("inactive"),dojo.query(this.app.modalRegionSingleton.overlayElement).addClass("active"));this.app.modalRegionSingleton.positionContent()},deactivate:function(){dojo.query(this.app.modalRegionSingleton.domElement).removeClass("active");dojo.query(this.app.modalRegionSingleton.domElement).addClass("inactive");dojo.query(this.app.modalRegionSingleton.overlayElement).removeClass("active");dojo.query(this.app.modalRegionSingleton.overlayElement).addClass("inactive");
if(this.app.modalRegionSingleton.activeView)this.app.modalRegionSingleton.activeView=null},host:function(a){this.app.modalRegionSingleton.inherited(arguments);this.app.modalRegionSingleton.domElement=a;dojo.query(this.app.modalRegionSingleton.domElement).removeClass("active");dojo.query(this.app.modalRegionSingleton.domElement).addClass("inactive");this.app.modalRegionSingleton.contentContainer=dojo.query(".modal-container",this.root)[0];this.app.modalRegionSingleton.contentElement=dojo.query(".modal-container-inner",
this.root)[0];this.app.modalRegionSingleton.overlayElement=dojo.query(".modal-overlay",this.root)[0];var b=this;dojo.connect(window,"onresize",function(){b.app.modalRegionSingleton.positionContent()});dojo.connect(window,"onscroll",function(){b.app.modalRegionSingleton.handleScrollEvent()})},handleScrollEvent:function(){if(this._scrollTimer!=null)clearTimeout(this._scrollTimer),this._scrollTimer=null;var a=this;this._scrollTimer=setTimeout(function(){a.positionOverlay()})},positionOverlay:function(a,
b){dojo.position(this.app.modalRegionSingleton.contentContainer);dojo.window.getBox();dojo.style(this.app.modalRegionSingleton.overlayElement,{left:"0px",top:"0px",width:a+"px",height:b+"px"})},positionContent:function(){if(this.app.modalRegionSingleton.contentContainer&&this.activeView!=null&&this.activeView.root!=null){var a=dojo.position(this.app.modalRegionSingleton.contentContainer),b=dojo.window.getBox(),c=document.all?document.scrollLeft:window.pageXOffset,d=document.all?document.scrollTop:
window.pageYOffset;c==void 0&&(c=0);d==void 0&&(d=0);this.positionOverlay(b.w,b.h,c,d);var e=a.w;a.w>b.w?(e=b.w,dojo.style(this.app.modalRegionSingleton.contentElement,{"max-width":e+"px"})):dojo.style(this.app.modalRegionSingleton.contentElement,{"max-width":""});var f=a.h;a.h>b.h?(f=b.h,dojo.style(this.app.modalRegionSingleton.contentElement,{"max-height":f+"px"})):dojo.style(this.app.modalRegionSingleton.contentElement,{"max-height":""});dojo.style(this.app.modalRegionSingleton.contentContainer,
{left:b.w/2-e/2+c+"px",top:b.h/2-f/2+d+"px"})}},showActiveView:function(a){if(a.isActive)this.app.modalRegionSingleton.activeView=a,this.app.modalRegionSingleton.hideAllViews(),a.activated(),this.app.modalRegionSingleton.activate(),this.app.modalRegionSingleton.activeView=a,this.app.modalRegionSingleton.positionContent(),dojo.removeClass(a.root,"inactive"),dojo.addClass(a.root,"active")},hideAllViews:function(){dojo.query("> .view",this.app.modalRegionSingleton.contentElement).removeClass("active");
dojo.query("> .view",this.app.modalRegionSingleton.contentElement).addClass("inactive")},activateView:function(a){Array.contains(this.app.modalRegionSingleton.activeViews,a)&&Array.removeItem(this.app.modalRegionSingleton.activeViews,a);this.app.modalRegionSingleton.activeViews.push(a);this.inherited(arguments);this.app.modalRegionSingleton.showActiveView(a);this.app.modalRegionSingleton.positionContent();this._repositionOnImageLoaded(a.root)},deactivateView:function(a){Array.removeItem(this.app.modalRegionSingleton.activeViews,
a);this.app.modalRegionSingleton.activeViews.length>0?(this.app.modalRegionSingleton.showActiveView(this.app.modalRegionSingleton.activeViews[this.app.modalRegionSingleton.activeViews.length-1]),this.app.modalRegionSingleton.positionContent()):this.app.modalRegionSingleton.deactivate();this.inherited(arguments)},deactivateActiveView:function(){if(this.app.modalRegionSingleton.activeView){if(this.app.modalRegionSingleton.titleBindingToken!=null)this.app.modalRegionSingleton.activeView.title.unbind(this.app.modalRegionSingleton.titleBindingToken),
this.app.modalRegionSingleton.titleBindingToken=null;var a=this.app.modalRegionSingleton.activeView;this.app.modalRegionSingleton.activeView=null;this.app.modalRegionSingleton.deactivateView(a);Array.removeItem(this.app.modalRegionSingleton.activeViews,this.app.modalRegionSingleton.activeView)}},hostView:function(a){this.app.modalRegionSingleton.views.push(a);if(a.markupResource){var b=geocortex.resourceManager.fetch(a.markupResource,a.libraryId);if(b==null)return this.app.trace.warning("Could not fetch markup resource '{0}'.".format(a.markupResource)),
false;else a.root=dojo.create("div",{className:"view"}),a.root.innerHTML=b,dojo.place(a.root,this.app.modalRegionSingleton.contentElement,"last"),this.app.viewManager.discoverRegions(a.root,a),this.app.modalRegionSingleton.positionContent()}a.viewModel&&a.attach(a.viewModel);this.inherited(arguments);return true},unhostView:function(a){a==this.app.modalRegionSingleton.activeView&&this.app.modalRegionSingleton.deactivateView(a);Array.removeItem(this.app.modalRegionSingleton.views,a);Array.removeItem(this.app.modalRegionSingleton.activeViews,
a);var b=new dojo.NodeList;b.push(a.root);b.orphan();this.inherited(arguments)},_repositionOnImageLoaded:function(a){var b=this;dojo.forEach(dojo.query("img",a),function(a){a.attached_ModalRegion_ImageLoadedConnection&&(dojo.disconnect(a.attached_ModalRegion_ImageLoadedConnection),Array.removeItem(a,a.attached_ModalRegion_ImageLoadedConnection));var d=dojo.connect(a,"load",b,function(a){b._imageLoaded(a)});a.attached_ModalRegion_ImageLoadedConnection=d})},_imageLoaded:function(a){a=a.target;a.attached_ModalRegion_ImageLoadedConnection&&
(dojo.disconnect(a.attached_ModalRegion_ImageLoadedConnection),Array.removeItem(a,a.attached_ModalRegion_ImageLoadedConnection));this.positionContent()}});
dojo.declare("geocortex.framework.storage.StorageProviderBase",null,{constructor:function(a,b,c){this.app=a;this._initializationSuccessCallback=b||function(){};this._initializationErrorCallback=c||function(){}},_initializationSuccessCallback:null,_initializationErrorCallback:null,_keyNamespace:null,isSupported:function(){return false},isFull:function(){return false},getStats:function(){return new geocortex.framework.storage.StorageStats},getScore:function(){return 0},initialize:function(){},clear:function(){},
clearAllData:function(){},get:function(){},set:function(){},remove:function(){}});geocortex.framework=geocortex.framework;geocortex.framework.application=geocortex.framework.application;geocortex.framework.commands=geocortex.framework.commands;geocortex.framework.config=geocortex.framework.config;geocortex.framework.events=geocortex.framework.events;geocortex.framework.storage=geocortex.framework.storage;geocortex.framework.ui=geocortex.framework.ui;geocortex.framework.utils=geocortex.framework.utils;
dojo.declare("geocortex.framework.application.Application",null,{constructor:function(a,b){this.id="default";geocortex.framework.registerApplication(this);this.configuration={};typeof a==="object"?(this._configModel=a,this._configUri=null):(this._configModel=null,this._configUri=a.trim());this.hostElement=b||dojo.body();this._injectedStyleBlocks=[];this._resourceDictionaries=[];this.eventRegistry=new geocortex.framework.events.EventRegistry;this.trace=new geocortex.framework.utils.Trace(this);this.commandRegistry=
new geocortex.framework.commands.CommandRegistry(this);this.moduleManager=new geocortex.framework.application.ModuleManager(this);this.viewManager=new geocortex.framework.ui.ViewManager(this);this.isOffline=new Observable(false);this.isOffline.bind(this,function(a){a?this.eventRegistry.event("ApplicationOfflineEvent").publish():this.eventRegistry.event("ApplicationOnlineEvent").publish()});geocortex.framework.application.ApplicationCommands.createCommands(this);var c=document.URL,c=c.substring(c.indexOf("?")+
1,c.length);this.urlParameters=dojo.queryToObject(c)||{};c=window.location.protocol;c.indexOf(":")<0&&(c+=":");var d=window.location.pathname.lastIndexOf("/"),e="/";d>-1&&(e=window.location.pathname.substr(0,d));e==""&&(e="/");this._host=c+"//"+window.location.host.trim()+e.trim();this._host.charAt(this._host.length-1)!="/"&&(this._host+="/");this.isHttpsMode=this.isHttpsUri(this._host);this._detectBrowserLocale()},_version:"1.1",hostElement:null,id:null,configuration:null,isOffline:null,locale:null,
urlParameters:null,developmentMode:false,proxyUri:null,isHttpsMode:false,initializationCompleteCallback:null,trace:null,moduleManager:null,commandRegistry:null,eventRegistry:null,viewManager:null,_configUri:"",_configModel:null,_host:null,_pendingLibraryDownloads:0,_pendingLocaleDownloads:0,_injectedStyleBlocks:null,_resourceDictionaries:null,_detectBrowserLocale:function(){this.locale=navigator.userLanguage?navigator.userLanguage:navigator.language?navigator.language:"inv"},isHttpsUri:function(a){a=
a.trim();return a.indexOf("://")>-1&&a.length>=5&&a.substring(0,5)=="https"},getUri:function(a){var b=false;return(b=a.indexOf("://")<0)?(a=this._host+a,this.isHttpsUri(a)!=this.isHttpsMode&&this.trace.warning("Mixing secured and non-secured resources. Request: '{0}'.".format(a)),this.proxyUri!=null&&!String.isNullOrEmpty(this.proxyUri)?this.proxyUri+encodeURIComponent(a):a):(this.isHttpsUri(a)!=this.isHttpsMode&&this.trace.warning("Mixing secured and non-secured resources. Request: '{0}'.".format(a)),
this.proxyUri+encodeURIComponent(a))},notifyLibraryDownload:function(a){this.trace.info("Downloaded library '{0}'.".format(a));this.eventRegistry.event("LibraryDownloadedEvent").publish(a);for(var b=geocortex.resourceManager.fetchAllFor(a,"css"),c="",d=dojo.query("head")[0],e=0;e<b.length;++e){var f=b[e],i=geocortex.resourceManager.fetch(f.name,f.library);i?c+=i+" ":this.trace.warning("Error decoding style resource '{0}' from library '{1}' - resource could not be found or was invalid.".format(f.name,
a))}b=document.createElement("style");this._injectedStyleBlocks.push(b);b.setAttribute("type","text/css");d.appendChild(b);b.styleSheet?b.styleSheet.cssText=c:(c=document.createTextNode(c),b.appendChild(c));if((c=geocortex.resourceManager.fetchAllFor(a,"json"))&&c.length>0)for(d=0;d<c.length;++d)b=c[d],e=geocortex.resourceManager.fetch(b.name,b.library,b.locale),this.injectLibraryResources(a,e,b.locale);c=this._configModel.libraryModules[a];c==null?this.trace.error("No modules found for library '{0}'.".format(a)):
(this._initializeModules(c),--this._pendingLibraryDownloads,this._pendingLibraryDownloads==0&&(resourceManager&&geocortex.resourceManager.performThemeInjection(),this.eventRegistry.event("ViewerLibrariesDownloadedEvent").publish(null)))},initialize:function(){var a=this;this.store=new geocortex.framework.storage.Store(this,this.id);this.store.initialize();dojo.connect(window,"onresize",function(){a.eventRegistry.event("ApplicationResizeEvent").publish();a.eventRegistry.event("ApplicationResizedEvent").publish()});
var b=new geocortex.framework.config.ConfigurationLoader(this),c=function(b){(new geocortex.framework.config.ConfigurationModel(a)).parse(b,function(b){a._processConfiguration(b)})};if(this._configModel!=null)c(this._configModel);else{var d=this._configUri,e=new dojo._Url(window.location),f=new dojo._Url(d);if(e.host)e.host=e.host.toLowerCase();if(f.host)f.host=f.host.toLowerCase();if(f.host&&e.host!=f.host)throw Error("Cannot load cross-domain configuration.");if(!f.host){e="{0}//{1}{2}".format(window.location.protocol,
window.location.host,window.location.pathname);if(e.charAt(e.length-1)!="/"||e.charAt(e.length-1)!="\\")e=e.split("/"),--e.length,e=e.join("/"),e+="/";if(d.charAt(0)=="/"||d.charAt(0)=="\\")d=window.location.protocol+"//"+window.location.host+"/"+d.substring(1)}b.loadConfigurationTree(d,function(a){c(a)})}this.viewManager.discoverRegions(this.hostElement)},shutdown:function(a){this.eventRegistry.event("ApplicationShutdownEvent").publish(a);this.viewManager.shutdown();this.moduleManager.shutdown(a);
this.commandRegistry.clear();this.eventRegistry.clear();for(a=0;a<this._injectedStyleBlocks.length;++a)dojo.destroy(this._injectedStyleBlocks[a]);this._injectedStyleBlocks=[]},injectLibraryResources:function(a,b,c){c=c.toLowerCase();this._resourceDictionaries.hasOwnProperty(c)===false?(this._resourceDictionaries[c]={},this._resourceDictionaries[c][a]=b):this._resourceDictionaries[c].hasOwnProperty(a)===false?this._resourceDictionaries[c][a]=b:dojo.mixin(this._resourceDictionaries[c][a],b)},getResource:function(a,
b,c){var c=c||this.locale||"inv",c=c.toLowerCase(),c=this._resourceDictionaries[c],d=this._resourceDictionaries.inv;c||(c=d);var e=c[a]||d[a];if(!e)return this.trace.warning("No resource dictionary found for library '{0}'.".format(a)),"@{0}".format(b);if(e.hasOwnProperty(b)===false)if(c===d)return"@{0}".format(b);else if(e=d[a],e.hasOwnProperty(b)===false)return this.trace.warning("The resource with key '{0}' was not found in library '{1}'.".format(b,a)),"@{0}".format(b);return e[b]},_processConfiguration:function(a){this.configuration=
a.applicationConfiguration||{};this._configModel=a;if(this.configuration&&this.configuration.locale)this.locale=this.configuration.locale;if(this.urlParameters&&this.urlParameters.locale)this.locale=this.urlParameters.locale;this._pendingLocaleDownloads=a.externalLocaleReferences.length;if(this._pendingLocaleDownloads==0)this._downloadLibraries(a);else for(var b=this,c=function(c,d){try{if(d)if(d.hasOwnProperty("locales"))for(var e in d)d.hasOwnProperty(e)&&b.injectLibraryResource(c.libraryId,d[e],
e);else if(c.hasOwnProperty("locale"))b.injectLibraryResources(c.libraryId,d,c.locale);else throw Error("Locale reference missing 'locale' identifier.");else b.trace.warning("Error loading locale '{0}' for library '{1}' from offline storage.".format(c.locale,c.libraryId))}catch(l){b.trace.error("Error fetching external locale resource {0}: {1}".format(c.uri,l.message))}finally{--b._pendingLocaleDownloads,b._pendingLocaleDownloads<1&&b._downloadLibraries(a)}},d=function(c,d){b.trace.error("Error fetching external locale resource {0}: {1}".format(c.uri,
d.message));--b._pendingLocaleDownloads;b._pendingLocaleDownloads<1&&b._downloadLibraries(a)},e=0;e<a.externalLocaleReferences.length;++e)(function(a){b.isOffline.get()===true?b.store.get("__locale_{0}".format(a.uri),function(b){b&&(b=geocortex.framework.utils.base64Decode(b));c(a,b)},d):dojo.xhrGet({url:a.uri,handleAs:"json",load:function(b){c(a,b)},error:function(b){d(a,b)}})})(a.externalLocaleReferences[e])},_downloadLibraries:function(a){this._pendingLibraryDownloads=a.libraryConfigs.length;for(var b=
0;b<a.libraryConfigs.length;++b){var c=a.libraryConfigs[b];geocortex.framework.hasLibrary(c.id)==true?this.notifyLibraryDownload(c.id):this.includeScript(c.uri,function(){},function(){})}},_translateConfiguration:function(a,b){var c=this,d=function(b,e){if(typeof e==="string"&&e.indexOf("@language")>-1){var f=e.split("-");if(f.length<2)throw Error("Invalid language key '{0}'.".format(e));f=f.join("-").replace("@","");return c.getResource(a,f)}else if(e instanceof Array){for(var h=[],j=0;j<e.length;++j)f=
{},f=d(j,e[j]),h.push(f);return h}else if(e instanceof Function)return e;else if(e instanceof Object){f={};for(h in e)f[h]=d(h,e[h]);return f}else return e},e={},f;for(f in b)e[f]=d(f,b[f]);return e},_initializeModules:function(a){for(var b={},c=0;c<a.length;++c){var d=a[c],e=this._translateConfiguration(d.libraryId,d.configuration),f=this.moduleManager.instantiate(d.moduleType);if(f==null)this.trace.error("Could not instantiate module with type '{0}' - type not found or constructor failed.".format(d.moduleType));
else{f.libraryId=d.libraryId;if(f.initialize){this.trace.info("Initializing module '{0}'.".format(d.moduleName));try{f.initialize(e)}catch(i){this.trace.error("Error initializing module '{0}': {1}.".format(d.moduleName,i.message));continue}this.moduleManager.markModuleLoaded(d.moduleName,f);this.trace.debug("Module '{0}' initialized.".format(d.moduleName))}if(d.viewModelConfigs&&d.viewModelConfigs.length>0){viewModelEntrys={};for(f=0;f<d.viewModelConfigs.length;++f){var k=d.viewModelConfigs[f];if(viewModelEntrys[k.viewModelID])this.trace.error("ViewModel '{0}' already exists in module '{1}'.".format(k.viewModelId,
d.moduleName));else{var l=dojo.getObject(k.typeName,true),h=null;try{h=new l(this,d.libraryId),h.app=this,h.id=k.viewModelId,h.libraryId=d.libraryId,e=this._translateConfiguration(d.libraryId,k.configuration),h.initialize(e),b[k.viewModelId]=h}catch(j){this.trace.error("Could not create view model with type '{0}' - type was not found, not a view model, or failed to construct: {1}".format(k.typeName,j.message))}}}}}}for(c=0;c<a.length;++c)if(d=a[c],d.viewConfigs)for(f=0;f<d.viewConfigs.length;++f)e=
d.viewConfigs[f],e=this._translateConfiguration(d.libraryId,e),e.libraryId=d.libraryId,(k=this.viewManager.createView(e))?e.viewModelId==null?(l=new geocortex.framework.ui.ViewModelBase(this),k.attach(l)):(l=b[e.viewModelId])?(k.attach(l),l.libraryId=d.libraryId):this.trace.error("Could not attach view model '{0}' to view '{1}' - view model not found.".format(e.viewModelId,e.viewId)):this.trace.warning("Could not instantiate view with type '{0}'.".format(e.typeName));if(this.initializationCompleteCallback)this._onInitializationComplete(),
this.initializationCompleteCallback=null},_onInitializationComplete:function(){this.initializationCompleteCallback!=null&&this.initializationCompleteCallback!=void 0&&this.initializationCompleteCallback()},includeScript:function(a,b,c){var d=this;this.isOffline.get()===true&&!this.urlParameters.hasOwnProperty("ffl")?this.store.get("__lib_{0}".format(a),function(b){if(b){d.trace.debug("Library '{0}' found in offline storage. Loading...".format(a));b=geocortex.framework.utils.base64Decode(b);try{eval.apply(window,
[b])}catch(c){d.trace.error("An error in a library file occurred: {0}".format(c))}d.trace.debug("Library '{0}' loaded.".format(a))}else d.trace.error("Library '{0}' was not found in offline storage.".format(a))},function(b){d.trace.error("An error occurred loading library '{0}' from offline storage: {1}".format(a,b))}):dojo.io.script.get({url:a,callbackParamName:"callback",preventCache:true,load:function(a){try{b&&b(a)}catch(c){this.trace.error("Error while including script '{0}': {1}".format(scriptPath,
c))}},error:function(a){c&&(this.trace.error("Error while including script '{0}': {1}".format(scriptPath,err)),c(a))}})}});dojo.provide("geocortex.framework.application.ApplicationCommands");dojo.declare("geocortex.framework.application.ApplicationCommands",null,{});dojo.mixin(geocortex.framework.application.ApplicationCommands,{createCommands:function(a){a.commandRegistry.command("OpenWebPage").register(a,function(a){window.open(a,"_blank")})}});
dojo.declare("geocortex.framework.application.ModuleBase",null,{constructor:function(a){this.app=a},app:null,libraryId:null,initialize:function(){},shutdown:function(){},getResource:function(a,b){return this.app.getResource(this.libraryId,a,b)}});
dojo.declare("geocortex.framework.application.ModuleManager",null,{constructor:function(a){this.app=a;this._modules={}},app:null,_modules:null,shutdown:function(a){for(var b in this._modules)this._modules.hasOwnProperty(b)&&this._modules[b].shutdown(a);this._modules={}},instantiate:function(a){var b=null;try{return b=dojo.getObject(a,true),new b(this.app)}catch(c){return null}},markModuleLoaded:function(a,b){this._modules[a]=b;this.app.eventRegistry.event("ModuleInitializedEvent").publish(a)},moduleIsLoaded:function(a){return this._modules[a]!=
null},notifyModuleLoaded:function(a,b){if(this.moduleIsLoaded(a)&&b!=null)b(a);else var c=this.app.eventRegistry.event("ModuleInitializedEvent").subscribe(this,function(d){if(d==a)try{b(d)}finally{this.app.eventRegistry.event("ModuleInitializedEvent").unsubscribe(c)}})}});
dojo.declare("geocortex.framework.application.ResourceManager",null,{constructor:function(){this._resources=[];this._themesToInject=[];this._cachedResources={}},_resources:null,_cachedResources:null,_themesToInject:null,fetch:function(a,b,c){var c=c||"inv",d="{0}-{1}-{2}".format(b,c,a);if(this._cachedResources.hasOwnProperty(d))return this._cachedResources[d];b=this._findResource(a,b,c);if(!b)return null;c=null;switch(b.format){case "css":case "html":c=geocortex.framework.utils.base64Decode(b.data);
this._cachedResources[d]=c;break;case "json":c=geocortex.framework.utils.base64Decode(b.data);c=dojo.fromJson(c);this._cachedResources[d]=c;break;default:a="Unknown resource type '{0}' for resource '{1}'.".format(b.format,a);try{console.error(a)}catch(e){throw Error(a);}return null}return c},fetchAllFor:function(a,b){for(var c=[],d=0;d<this._resources.length;++d){var e=this._resources[d];e.library==a&&!(b!=null&&e.format!=b)&&c.push(e)}return c},register:function(a,b,c,d,e){if(this._findResource(c,
a))throw Error("Library '{0}' attempted to re-register the resource '{1}'.".format(a,c));var f={};f.name=c;f.library=a;f.locale=b;f.format=d;f.data=e;this._resources.push(f)},remove:function(a,b,c){var d=this._findResource(b,a,c);return d!=null?(Array.removeItem(this._resources,d),a="{0}-{1}-{2}".format(a,c,b),this._cachedResources.hasOwnProperty(a)&&Array.removeItem(this._cachedResources,this._cachedResources[a]),true):false},_findResource:function(a,b,c){for(var c=c||"inv",d=0;d<this._resources.length;++d){var e=
this._resources[d];if(e.name==a&&!(b!=null&&e.library!=b)&&e.locale==c)return e}return null},injectTheme:function(a){this._themesToInject.push(a)},performThemeInjection:function(){for(var a=dojo.query("head")[0],b=0;b<this._themesToInject.length;++b){var c=dojo.create("link",{rel:"stylesheet",href:this._themesToInject[b]});dojo.place(c,a,"last")}}});
dojo.declare("geocortex.framework.commands.Command",null,{constructor:function(a,b,c){this.name=a;this.app=b;this.canExecuteChanged=new geocortex.framework.events.Event;this.isWrapper=true;this._canExecutes=[];this._executes=[];this._scopes=[];this.canExecuteMode=c!=null?c:"all"},app:null,name:"",isWrapper:true,_canExecutes:null,_executes:null,_scopes:null,canExecuteMode:"all",canExecuteChanged:null,canExecute:function(a){if(this.isWrapper)return false;for(var b=0;b<this._canExecutes.length;++b){var c=
this._canExecutes[b];if(c&&c.apply(this,arguments)){if(this.canExecuteMode=="any")return true}else if(this.canExecuteMode=="all")return false}return this.canExecuteMode=="any"?false:true},execute:function(a){if(!this._executes||this._executes.length==0)this.app.trace.debug("Command '{0}' executed but no implementation registered.".format(this.name));else if(this.canExecuteMode!="all"||this.canExecute.apply(this,arguments))for(var b=0;b<this._executes.length;++b){var c=this._executes[b],d=this._canExecutes[b],
e=this._scopes[b];(this.canExecuteMode!="any"||d.apply(e,arguments))&&c.apply(e,arguments)}},register:function(a,b,c){this.isWrapper=false;this._scopes.push(a);this._executes.push(b);c?this._canExecutes.push(c):this._canExecutes.push(function(){return true});this.app.trace.debug("Registered an implementation for command '{0}'.".format(this.name))},clear:function(){this._executes=[];this._canExecutes=[];this._scopes=[]}});
dojo.declare("geocortex.framework.commands.CommandRegistry",null,{constructor:function(a){this.commands={};this.app=a},app:null,commands:null,clear:function(){for(var a in this.commands)this.commands.hasOwnProperty(a)&&this.commands[a].clear()},command:function(a){var b=this.commands[a];return!b?(a=new geocortex.framework.commands.Command(a,this.app),a.isWrapper=true,this.commands[a.name]=a):b}});
dojo.declare("geocortex.framework.config.ConfigurationLoader",null,{constructor:function(a){this.app=a},app:null,_targetConfigUri:null,loadConfigurationTree:function(a,b){this._targetConfigUri=a;var c=this,d=function(a){c.app.eventRegistry.event("ConfigurationLoadFailedEvent").publish(a)};if(this.app.isOffline.get()===true){var e=this;this.app.store.get("__config_"+a,function(c){c?(e.app.trace.debug("Configuration found in offline storage."),b&&b(c)):(c="No offline configuration for this application was found. Configuration: {0}".format(a),
e.app.trace.error(c),d(Error(c)))},function(a){e.app.trace.error("An error occurred when fetching offline configuration. The application could not start in offline mode.");d(a)})}else dojo.xhrGet({url:this._targetConfigUri,load:function(a){b!=null&&b!=void 0&&b(a)},error:d})}});
dojo.declare("geocortex.framework.config.ConfigurationModel",null,{constructor:function(a){this.app=a;this.applicationConfiguration={};this.globals=[];this.libraryConfigs=[];this.moduleConfigs=[];this.libraryModules={};this.externalLocaleReferences=[]},app:null,applicationConfiguration:null,version:"unknown",defaultLibraryId:"",globals:null,libraryConfigs:null,moduleConfigs:null,libraryModules:null,externalLocaleReferences:null,parse:function(a,b){var c=typeof a==="object"?a:dojo.fromJson(a),d=[],
e=[];try{this.applicationConfiguration=c.configuration.application||{},this.version=c.configuration.version||"1.0",this.defaultLibraryId=c.configuration.defaultLibraryId||null,e=c.configuration.libraries,d=c.configuration.modules,this.app.trace.debug("Config version: {0}.".format(this.version))}catch(f){this.app.trace.error("Error reading configuration: {0}".format(f));return}if(e&&e.length>0)for(var i=0;i<e.length;++i){var k=e[i];if(this.defaultLibraryId==null)this.defaultLibraryId=k.id;var l=new geocortex.framework.config.LibraryConfig(k.id,
k.uri);this.libraryConfigs.push(l);this.libraryModules[k.id]=[];if(k.locales&&k.locales instanceof Array)for(c=0;c<k.locales.length;++c){var h=k.locales[c];h.locale=h.locale.toLowerCase();if(h.hasOwnProperty("uri"))h.libraryId=k.id,l.locales.push(h),this.externalLocaleReferences.push(h)}}if(d&&d.length>0)for(c=0;c<d.length;++c){e=d[c];i=e.libraryId;if(!i)i=this.defaultLibraryId;k=new geocortex.framework.config.ModuleConfig(e.moduleName,e.moduleType,e.configuration,i);this.libraryModules[i]?this.libraryModules[i].push(k):
this.app.trace.error("Unknown library '{0}'.".format(i));if(h=e.views)for(l=0;l<h.length;++l){var j=h[l],g=new geocortex.framework.config.ViewConfig(j.id,e.moduleName,j.type||"geocortex.framework.ui.ViewBase");k.viewConfigs.push(g);g.libraryId=i;g.viewModelId=j.viewModelId||null;g.markupResource=j.markup||null;g.configuration=j.configuration||{};g.regionName=j.region||null;g.isManaged=j.isManaged||false;g.isVisible=j.visible||false;g.title=j.title||null;g.description=j.description||"";g.iconUri=j.iconUri||
""}if(h=e.viewModels)for(l=0;l<h.length;++l)if(j=h[l],g=new geocortex.framework.config.ViewModelConfig(j.id,e.moduleName,j.type),k.viewModelConfigs.push(g),g.libraryId=i,j.configuration)g.configuration=j.configuration;this.moduleConfigs.push(k)}b(this)}});dojo.declare("geocortex.framework.config.LibraryConfig",null,{constructor:function(a,b){this.id=a;this.uri=b;this.locales=[]},id:"",uri:"",locales:[]});
dojo.declare("geocortex.framework.config.ModuleConfig",null,{constructor:function(a,b,c,d){this.moduleName=a;this.moduleType=b;this.configuration=c;this.libraryId=d;this.viewConfigs=[];this.viewModelConfigs=[]},libraryId:"",moduleName:"",moduleType:"",configuration:"",viewConfigs:null,viewModelConfigs:null});
dojo.declare("geocortex.framework.config.ViewConfig",null,{constructor:function(a,b,c){this.viewId=a;this.moduleNameArg=b;this.typeName=c},viewId:"",viewModelId:null,libraryId:"",moduleName:"",configuration:"",typeName:"",markupResource:"",regionName:"",isVisible:true,isManaged:false,title:"",description:"",iconUri:null});
dojo.declare("geocortex.framework.config.ViewModelConfig",null,{constructor:function(a,b,c){this.viewModelId=a;this.moduleNameArg=b;this.typeName=c},viewModelId:"",libraryId:"",moduleName:"",typeName:"",configuration:""});dojo.declare("geocortex.framework.events.CollectionChangedArgs",null,{constructor:function(){this.sender=null;this.type="append";this.rangeEnd=this.rangeStart=0},sender:null,type:null,rangeStart:0,rangeEnd:0});
dojo.declare("geocortex.framework.events.Event",null,{constructor:function(a){this.name=a;this.subscriptions=[]},name:"",subscriptions:null,getSubscriptionHandlerByToken:function(a){for(var b=0;b<this.subscriptions.length;++b)if(sub.token==a)return sub.handler;return null},subscribe:function(a,b){for(var c=geocortex.framework.utils.alphaNumericToken();this.getSubscriptionHandlerByToken[c];)c=geocortex.framework.utils.alphaNumericToken();var d={};d.handler=b;d.token=c;d.scope=a;this.subscriptions.push(d);
return c},publish:function(a){for(var b=0;b<this.subscriptions.length;++b){var c=this.subscriptions[b];c.handler.apply(c.scope,arguments)}},unsubscribe:function(a){for(var b=0;b<this.subscriptions.length;++b)if(this.subscriptions[b].token==a)return Array.remove(this.subscriptions,b),true;return false},clear:function(){this.subscriptions={}}});
dojo.declare("geocortex.framework.events.EventRegistry",null,{constructor:function(){this.events={}},events:null,clear:function(){for(var a in this.events)this.events.hasOwnProperty(a)&&this.events[a].clear()},event:function(a){var b=this.events[a];b||(b=new geocortex.framework.events.Event(a),this.events[a]=b);return b}});
dojo.declare("geocortex.framework.events.Observable",null,{constructor:function(a){this.value=a;this._syncSource=this._syncToken=null;this.bindingEvent=new geocortex.framework.events.Event("__anonymous")},value:null,isObservable:true,bindingEvent:null,_syncToken:null,set:function(a){this.value=a;this.bindingEvent.publish(a)},get:function(){return this.value},pulse:function(){this.set(this.get())},bind:function(a,b){return this.bindingEvent.subscribe(a,b)},unbind:function(a){return this.bindingEvent.unsubscribe(a)},
sync:function(a){if(this._syncToken&&this._syncSource)this._syncSource.unbind(this._syncToken),this._syncSource=this._syncToken=null;if(a)this.set(a.get()),this._syncSource=a,this._syncToken=a.bindingEvent.subscribe(this,function(a){this.set(a)})}});
geocortex.framework.events.Observable.makeBindableProxy=function(a){if(!a)return null;var b=[];if(a.___clonedObject)return a.___clonedObject;var c=function(){throw Error("Can't make method calls on a bindable proxy.");},d=function(a,e,k){for(var l=0;l<b.length;++l)if(e===b[l])return b[l];b.push(e);if(!e||typeof e==="string"||typeof e==="number"||typeof e==="boolean"){var h=new Observable(e);(function(){h.set=function(b){k[a]=b;h.value=b;h.bindingEvent.publish(b)};h.get=function(){return k[a]}})();
return h}else if(e instanceof Array){for(var j=new ObservableCollection([]),l=0;l<e.length;++l){var g={},g=d(l,e[l],e);j.addItem(g)}return j}else if(e instanceof Object){if(e.isObservable)return e;g={};for(j in e)g[j]=d(j,e[j],e);return g}else return e instanceof Function?c:e},e=d("root",{root:a},a);a.___clonedObject=e.root;return a instanceof Array?e.root:new Observable(e.root)};
dojo.declare("geocortex.framework.events.ObservableCollection",geocortex.framework.events.Observable,{constructor:function(a){this.value=a||[]},isObservableCollection:true,useThrottling:false,isEmpty:function(){if(!this.value)this.value=[];return this.value.length==0},length:function(){if(!this.value)this.value=[];return this.value.length},contains:function(a){if(!this.value)this.value=[];return Array.contains(this.value,a)},getAt:function(a){return this.value[a]},getItems:function(){if(!this.value)this.value=
[];return this.value},getLength:function(){if(!this.value)this.value=[];return this.value.length},addItems:function(a){if(!this.value)this.value=[];if(a&&!(a.length<1)){var b=new geocortex.framework.events.CollectionChangedArgs;b.type="append";b.rangeStart=this.value.length;this.value=this.value.concat(a);b.rangeEnd=b.rangeStart+a.length-1;b.sender=this;this.bindingEvent.publish(b)}},addItem:function(a){if(!this.value)this.value=[];var b=new geocortex.framework.events.CollectionChangedArgs;b.type=
"append";b.rangeStart=this.value.length;b.rangeEnd=this.value.length;this.value.push(a);b.sender=this;this.bindingEvent.publish(b)},insertItems:function(a,b){if(!this.value)this.value=[];if(b.length!=0)if(a>=this.value.length)this.addItems(b);else{var c=new geocortex.framework.events.CollectionChangedArgs;c.type="insert";c.rangeStart=a;c.rangeEnd=a+b.length-1;c.sender=this;for(var d=0;d<b.length;++d)this.value.splice(a+d,0,b[d]);this.bindingEvent.publish(c)}},insertItem:function(a,b){if(!this.value)this.value=
[];if(a>=this.value.length)this.addItem(b);else{var c=new geocortex.framework.events.CollectionChangedArgs;c.type="insert";c.rangeStart=a;c.rangeEnd=a;c.sender=this;this.value.splice(a,0,b);this.bindingEvent.publish(c)}},removeItem:function(a){if(!this.value)this.value=[];for(var b=Array.pos(this.value,a);b>-1;){var c=new geocortex.framework.events.CollectionChangedArgs;c.type="remove";c.rangeStart=b;c.rangeEnd=b;c.sender=this;this.bindingEvent.publish(c);Array.remove(this.value,b,b);b=Array.pos(this.value,
a)}},clear:function(){if(this.value&&this.value.length!=0){var a=new geocortex.framework.events.CollectionChangedArgs;a.type="clear";a.rangeStart=0;a.rangeEnd=this.value.length-1;a.sender=this;this.bindingEvent.publish(a);this.value=[]}},set:function(a){this.clear();a&&this.addItems(a)},sync:function(a){if(a.value&&a.bindingEvent)this.clear(),this.value=a.value,a.bindingEvent.subscribe(this,function(b){this.value=a.value;b=dojo.mixin({},b);b.sender=this;this.bindingEvent.publish(b)})}});
dojo.declare("geocortex.framework.events.ViewDimensionsChangedArgs",null,{region:null,view:null,constructor:function(a,b){this.view=a;this.region=b}});
dojo.declare("geocortex.framework.storage.FileStorageProvider",geocortex.framework.storage.StorageProviderBase,{constructor:function(){},_requestFileSystem:null,_filesystem:null,_isInitializing:false,_defaultDesiredSize:524288E3,_error:null,_isFull:null,_isInitialized:null,isSupported:function(){this.inherited(arguments);return window.requestFileSystem||window.webkitRequestFileSystem},isFull:function(){this.initialize();return this._isfull},getScore:function(){this.initialize();return 5},getStats:function(){this.initialize();
return new geocortex.framework.storage.StorageStats},_ensureInitializedThen:function(a){if(a)if(this._isInitialized)a.apply(this,[]);else if(!this._isInitializing){var b=this;this._isInitializing=true;dojo.connect(this,"_initializationSuccessCallback",function(){a.apply(b,[])});this.initialize()}},initialize:function(a){var b=this;if(!this._isInitialized&&!this._error)if(this.inherited(arguments),this.isSupported()){window.requestFileSystem=window.requestFileSystem||window.webkitRequestFileSystem;
if(!a&&(this.app.configuration&&this.app.configuration.offlineStorageSpaceMb&&(a=parseInt(this.app.configuration.offlineStorageSpaceMb)*1048576),!a))a=this._defaultDesiredSize;var c=function(a){if(!b._isInitialized)b._isInitialized=true,b.app.trace.debug("Filesystem '{0}' initialized successfully.".format(a.name)),b._filesystem=a,b._error=null,b._initializationSuccessCallback(a)};window.webkitStorageInfo?(window.webkitStorageInfo.queryUsageAndQuota(window.PERSISTENT,function(a,c){b.app.trace.debug("File API provider: {0} bytes used out of {1} byte quota. Remaining bytes: {2}".format(a,
c,c-a))},function(a){a=b._shapeError(a);b.app.trace.warning("An error occurred while trying to fetch file API usage information: {0}".format(a.toString()))}),window.webkitStorageInfo.requestQuota(window.PERSISTENT,a,function(d){this._isInitialized||(b.app.trace.debug("HTML5 File API quota granted. Size: {0} bytes.".format(d)),window.requestFileSystem(window.PERSISTENT,a,c,function(a){a=b._shapeError(a);b.error=a;b.errorHandler(a);b.initializationErrorCallback(a)}))},function(a){a=b._shapeError(a);
b._error=a;b.app.trace.error("Error requesting filesystem quota: {0}".format(a.toString()));b.errorHandler(a);b.initializationErrorCallback(a)}),setTimeout(function(){b._isInitialized||window.requestFileSystem(window.PERSISTENT,a,c,function(a){a=b._shapeError(a);b.app.trace.error("Error requesting filesystem access: {0}".format(a.toString()));b.error=a;b.errorHandler(a);b.initializationErrorCallback(a)})},1)):this._requestFileSystem(window.PERSISTENT,a,c,function(a){a=b._shapeError(a);b.error=a;b.errorHandler(a);
b.initializationErrorCallback(a)})}else this.app.trace.warning("The HTML5 storage provider could not be initialized. The File API is not supported by this browser.")},_writeValue:function(a,b,c,d){function e(a,b){b=f._shapeError(b);d&&d(b,a)}var f=this;try{f._filesystem.root.getFile(a+".json",{create:true,exclusive:false},function(k){k.createWriter(function(a){a.truncate(0)});k.createWriter(function(k){k.onwriteend=function(a){f.app.trace.debug("Wrote {0} bytes to filesystem.".format(a.total))};k.onerror=
function(a){a=f._shapeError(a);f.app.trace.debug("Write failed: {0}".format(a));d&&d(a)};var i=false;try{if(typeof device!=="undefined"&&device.cordova)k.write(b);else{var j=null;typeof BlobBuilder!=="undefined"?j=new BlobBuilder:typeof WebKitBlobBuilder!=="undefined"?j=new WebKitBlobBuilder:typeof MsBlobBuilder!=="undefined"&&(j=new MsBlobBuilder);if(!j)throw Error("Error writing to File API file: No BlobBuilder implementation found.");j.append(b);k.write(j.getBlob("text/plain"))}}catch(g){i=true,
e(a,g)}i||c()},function(b){e(a,b)})},function(b){e(a,b)})}catch(i){e(i)}},_readValue:function(a,b,c){function d(a){a.code&&a.code===FileError.NOT_FOUND_ERR?b(null):(a=e._shapeError(a),c&&c(a))}var e=this;this._ensureInitializedThen(function(){e._filesystem.root.getFile(a+".json",{},function(a){a.file(function(a){var c=new FileReader;c.onloadend=function(){b(this.result)};try{c.readAsText(a)}catch(e){d(e)}},d)},d)})},_shapeError:function(a){var b="";if(a.hasOwnProperty("code")){switch(a.code){case FileError.QUOTA_EXCEEDED_ERR:b=
"Quota Exceeded.";break;case FileError.NOT_FOUND_ERR:b="File not found.";break;case FileError.SECURITY_ERR:b="Security error.";break;case FileError.INVALID_MODIFICATION_ERR:b="Invalid modification.";break;case FileError.INVALID_STATE_ERR:b="Invalid state.";break;default:b="Unknown Error."}a=Error("File error: {0}.".format(b))}return a},clear:function(){this._ensureInitializedThen(function(){})},clearAllData:function(a,b){this.inherited(arguments);var c=this;this._ensureInitializedThen(function(){try{var d=
c._filesystem.root.createReader(),e=[],f=[],i=0,k=0,l=new dojo.Deferred,h=new dojo.Deferred,j=new dojo.DeferredList([l,h]);h.resolve();j.then(function(){k?b&&b(Error("{0} errors were encountered while clearing the storage provider.".format(k))):a&&a()});j.addErrback(function(a){b&&(a=c._shapeError(a),b(a))});var g=function(){var a=function(){--i;i<=0&&l.resolve()},b=function(a){a=c._shapeError(a);c.app.trace.debug("Error removing local file: {0}.".format(a.toString()));--i;++k;i<=0&&l.resolve()},
d=function(c){c.remove(a,b)},f=function(a){a=c._shapeError(a);c.app.debug.trace("Could not obtain file for removal: {0}.".format(a.toString()));h.errback()};i=e.length;if(i===0)l.resolve();else for(var g=0;g<e.length;++g)try{c._filesystem.root.getFile(e[g],{create:false},d,f)}catch(m){m=c._shapeError(m),j.errback(m)}},q=function(){d.readEntries(function(a){if(a.length){for(var b=0;b<a.length;++b){var c=a[b];c.isdirectory?f.push(c.fullPath):e.push(c.fullPath)}q()}else g()},function(a){a=c._shapeError(a);
b&&b(a)})};q()}catch(s){s=c._shapeError(s),b&&b(s)}})},get:function(a,b,c){this.inherited(arguments);var d=this;this._ensureInitializedThen(function(){try{d._readValue(a,b,c)}catch(e){e=d._shapeError(e),c&&c(e)}})},set:function(a,b,c,d){this.inherited(arguments);var e=this;this._ensureInitializedThen(function(){try{e._writeValue(a,b,c,d)}catch(f){f=e._shapeError(f),d&&d(f)}})},remove:function(a,b,c){this.inherited(arguments);var d=this;this._ensureInitializedThen(function(){try{d._filesystem.root.getFile(a+
".json",{create:false},function(a){a.remove(b,function(a){a=d._shapeError(a);c&&c(a)})},function(a){a=d._shapeError(a);d.app.debug.trace("Could not obtain file for removal: {0}.".format(a.toString()));c&&c(a)})}catch(e){e=d._shapeError(e),c&&c(e)}})}});
dojo.declare("geocortex.framework.storage.LocalStorageProvider",geocortex.framework.storage.StorageProviderBase,{constructor:function(){},_localStorage:null,_isFull:null,isSupported:function(){this.inherited(arguments);this._localStorage||this.initialize();return!!this._localStorage},isFull:function(){this._localStorage||this.initialize();return this._isfull},getScore:function(){this._localStorage||this.initialize();return 5},getStats:function(){this._localStorage||this.initialize();return new geocortex.framework.storage.StorageStats},
initialize:function(){this.inherited(arguments);this._localStorage=window.localStorage},clear:function(){this._localStorage||this.initialize()},clearAllData:function(a,b){this.inherited(arguments);this._localStorage||this.initialize();try{this._localStorage.clear(),a&&a()}catch(c){b&&b(c)}},get:function(a,b,c){this.inherited(arguments);this._localStorage||this.initialize();try{var d=this._localStorage.getItem(a);b&&b(d)}catch(e){c&&c(e)}},set:function(a,b,c,d){this.inherited(arguments);this._localStorage||
this.initialize();try{this._localStorage.setItem(a,b),c&&c(a)}catch(e){d&&d(e)}},remove:function(a,b,c){this.inherited(arguments);this._localStorage||this.initialize();try{this._localStorage.removeItem(a),b&&b()}catch(d){c&&c(d)}}});dojo.declare("geocortex.framework.storage.StorageStats",null,{capacity:this.UNKNOWN,sizeInChars:this.UNKNOWN,numKeys:this.UNKNOWN,UNKNOWN:-1});
dojo.declare("geocortex.framework.storage.Store",null,{constructor:function(a,b){this.app=a;this._rootNamespace=b?b:"framework."+this.app.id},app:null,_provider:null,_rootNamespace:null,_yield:function(a){return!a?function(){}:function(){var b=arguments;setTimeout(function(){a.apply(this,b)},0)}},initialize:function(a,b,c){a?this._provider=a:(a=new geocortex.framework.storage.FileStorageProvider(this.app,this._yield(b),this._yield(c)),this._provider=a.isSupported()?a:new geocortex.framework.storage.LocalStorageProvider(this.app,
this._yield(b),this._yield(c)))},clear:function(a,b){this._provider&&this._provider.clear(this._yield(a),this._yield(b))},clearAllData:function(a,b){this._provider&&this._provider.clearAllData(this._yield(a),this._yield(b))},_sanitizeKey:function(a){return a.replace(RegExp("[/\\:,?=]","gm"),"_")},set:function(a,b,c,d){var e=new dojo.Deferred,a=this._sanitizeKey(this._rootNamespace+"."+a);this._provider&&this._provider.set(a,b,this._yield(function(a){geocortex.deferredResolve(e,a);c&&c(a)}),this._yield(function(a){geocortex.deferredReject(e,
a);d&&d(a)}));return e},get:function(a,b,c){var d=new dojo.Deferred,a=this._sanitizeKey(this._rootNamespace+"."+a);this._provider&&this._provider.get(a,this._yield(function(a){geocortex.deferredResolve(d,a);b&&b(a)}),this._yield(function(a){geocortex.deferredReject(d,a);c&&c(a)}));return d},remove:function(a,b,c){a=this._sanitizeKey(this._rootNamespace+"."+a);this._provider&&this._provider.remove(a,this._yield(b),this._yield(c))}});
dojo.declare("geocortex.framework.ui.BindingExpression",null,{constructor:function(){this.domElement=null;this.type="attr";this.attributeName=null;this.domEventSubscriptions=[];this.templateKey=this.templateMode=null;this.templateSelections={};this.targetBindings=[];this.boundViews=[];this.viewModel=this.parentView=null},domElement:null,type:null,attributeName:null,target:null,invert:false,domEventSubscriptions:[],targetBindings:[],templateMode:null,templateKey:null,templateSelections:null,parentView:null,
boundViews:null,viewModel:null,destroy:function(){if(this.templateSelections)for(var a in this.templateSelections)if(this.templateSelections.hasOwnProperty(a)){var b=this.templateSelections[a];b&&b.___domParent&&dojo.place(b,b.___domParent,"last")}this.context=this.target=this.domElement=null;this.parentView=false;this.viewModel=null;for(a=0;a<this.domEventSubscriptions.length;++a)dojo.disconnect(this.domEventSubscriptions[a]);this.domEventSubscriptions=[];for(a=0;a<this.targetBindings.length;++a)this.targetBindings[a].event.unsubscribe(this.targetBindings[a].token);
this.targetBindings=[];for(a=0;a<this.boundViews.length;++a)this.boundViews[a].destroyBindings();this.boundViews=[]}});
dojo.declare("geocortex.framework.ui.BindingNode",null,{constructor:function(){this.context=this.parent=this.domElement=null;this.children=[];this.expressions=[]},domElement:null,parent:null,children:null,expressions:null,context:null,destroy:function(){this.context=this.parent=this.domElement=null;this.contextChange=false;for(var a=0;a<this.expressions.length;++a)this.expressions[a].destroy();this.expressions=[];for(a=0;a<this.children.length;++a)this.children[a].destroy();this.children=[]}});
dojo.declare("geocortex.framework.ui.DivRegionAdapter",geocortex.framework.ui.RegionAdapterBase,{constructor:function(a,b){this.name=a;this.app=b},activateView:function(a){this.inherited(arguments)},deactivateView:function(a){this.inherited(arguments)},unhostAllViews:function(){for(var a=0;a<this.views.length;++a)this.unhostView(this.views[a]);this.views=[]},hostView:function(a){this.unhostAllViews();this.views.push(a);if(a.markupResource){var b=geocortex.resourceManager.fetch(a.markupResource,a.libraryId);
if(b==null)return this.app.trace.warning("Could not fetch markup resource '{0}'.".format(a.markupResource)),false;else a.root=dojo.create("div",{className:"view"}),a.root.innerHTML=b,dojo.place(a.root,this.domElement,"only"),this.app.viewManager.discoverRegions(a.root,a)}a.viewModel&&a.attach(a.viewModel);this.inherited(arguments);return true},unhostView:function(a){this.deactivateView(a);Array.removeItem(this.views,a);var b=new dojo.NodeList;b.push(a.root);b.orphan();this.inherited(arguments)}});
dojo.declare("geocortex.framework.ui.DivStackRegionAdapter",geocortex.framework.ui.RegionAdapterBase,{constructor:function(a,b){this.app=b;this.name=a;this.activeViews=[];this.app=b},activeViews:null,activateView:function(a){Array.contains(this.activeViews,a)&&Array.removeItem(this.activeViews,a);this.activeViews.push(a);dojo.place(a.root,this.domElement,"last");this.inherited(arguments)},deactivateView:function(a){a.isActive=false;Array.removeItem(this.activeViews,a);this.activeViews.length>0&&this.activateView(this.activeViews[this.activeViews.length-
1]);this.inherited(arguments)},hostView:function(a){this.views.push(a);if(a.markupResource){var b=geocortex.resourceManager.fetch(a.markupResource,a.libraryId);if(b==null)return this.app.trace.warning("Could not fetch markup resource '{0}'.".format(a.markupResource)),false;else a.root=dojo.create("div",{className:"view"}),a.root.innerHTML=b,dojo.place(a.root,this.domElement,"last"),this.app.viewManager.discoverRegions(a.root,a)}a.viewModel&&a.attach(a.viewModel);this.inherited(arguments);return true},
unhostView:function(a){this.deactivateView(a);Array.removeItem(this.views,a);Array.removeItem(this.activeViews,a);var b=new dojo.NodeList;b.push(a.root);b.orphan();this.inherited(arguments)}});
dojo.declare("geocortex.framework.ui.MultiDivRegionAdapter",geocortex.framework.ui.RegionAdapterBase,{constructor:function(a,b){this.app=b;this.name=a;this.activeViews=[]},activeViews:null,activateView:function(a){this.hideAllViews();if(this.activeViews.length>0){var b=this.activeViews[this.activeViews.length-1];b!==a&&(this._cancelActivate(b),b.deactivated())}Array.contains(this.activeViews,a)&&Array.removeItem(this.activeViews,a);this.activeViews.push(a);this.inherited(arguments)},deactivateView:function(a,
b){if(b===void 0||b===null)b=true;Array.removeItem(this.activeViews,a);b&&this.activeViews.length>0&&this.activateView(this.activeViews[this.activeViews.length-1]);this.inherited(arguments)},hideAllViews:function(){dojo.query("> .view",this.domElement).removeClass("active");dojo.query("> .view",this.domElement).addClass("inactive")},hostView:function(a){this.views.push(a);if(a.markupResource){var b=geocortex.resourceManager.fetch(a.markupResource,a.libraryId);if(b==null)return this.app.trace.warning("Could not fetch markup resource '{0}'.".format(a.markupResource)),
false;else a.root=dojo.create("div",{className:"view"}),a.root.innerHTML=b,dojo.place(a.root,this.domElement,"last"),this.app.viewManager.discoverRegions(a.root,a)}a.viewModel&&a.attach(a.viewModel);this.inherited(arguments);return true},unhostView:function(a){this.deactivateView(a);Array.removeItem(this.views,a);Array.removeItem(this.activeViews,a);var b=new dojo.NodeList;b.push(a.root);b.orphan();this.inherited(arguments)}});
dojo.declare("geocortex.framework.ui.ViewBase",null,{constructor:function(a){this.app=a;this.id="View-"+geocortex.utils.alphaNumericToken();this.isActive=false;this.childRegions=[];this.isBusy=new Observable(false);this.title=new Observable("");this.description=new Observable("");this.iconUri=new Observable("");this._disposableBindings=[];this._bindingSetupDelegates=[]},app:null,id:null,isActive:null,configuration:null,isManaged:false,isBusy:null,title:null,description:null,iconUri:null,markupResource:null,
viewModel:null,regionName:"",typeName:"",root:null,libraryId:null,bindingTree:null,parentView:null,childRegions:null,bound:false,_disposableBindings:null,_bindingSetupDelegates:null,addDisposableBinding:function(a,b){this._disposableBindings.push({event:a.bindingEvent,token:b})},attach:function(a){this.viewModel=a;if(this.root)this.bindingTree=this.buildTree(),this.bound=true,this.viewModel&&this.pulseAll()},activated:function(){},deactivated:function(){},added:function(){if(!this.bound&&this.viewModel)this.bindingTree=
this.buildTree(),this.bound=true,this.pulseAll()},removed:function(){this.destroyBindings()},destroyBindings:function(){if(this.bindingTree){this.bindingTree.destroy();for(var a=0;a<this._disposableBindings.length;++a){var b=this._disposableBindings[a];b.event.unsubscribe(b.token)}this._disposableBindings=[];this._bindingSetupDelegates=[]}},pulseAll:function(){for(var a=0;a<this._bindingSetupDelegates.length;++a)try{this._bindingSetupDelegates[a]()}catch(b){this.app.trace.error("Error performing initial data-bind in view '{0}' with view model '{1}': {2}".format(this.id,
this.viewModel.id,b.message))}this._bindingSetupDelegates=[]},buildTree:function(){function a(c,e){function f(a){var b=[];if(!a)return b;var c=a.match(/\{(.*?)\}/g);if(!c)if(this.app)return this.app.trace.warning("Invalid data-binding expression '{0}'.".format(a)),[];else throw Error("Invalid data-binding expression '{0}'.".format(a));for(a=0;a<c.length;++a){var d=c[a].split(":");d.length==2&&b.push({directive:d[0].replace("{","").trim(),target:d[1].replace("}","").trim()})}return b}for(var i=0;i<
e.children.length;++i){var k=e.children[i],l=dojo.attr(k,"data-region-name"),h=dojo.attr(k,"data-binding");h||(h=k.___dataBindingExpressions);if(h){var j=f(h);k.___dataBindingExpressions=h;b.app.debugMode||dojo.removeAttr(k,"data-binding");if(j&&j.length!==0){for(var g=false,q=0;q<j.length;++q)(function(){var a=c.expressions,e=c.context,i=false,h=j[q],n=h.directive,l=h.target,m=new geocortex.framework.ui.BindingExpression;m.app=b.app;m.type="attr";m.domElement=k;m.attributeName=null;m.target=l;m.invert=
false;m.domEventSubscriptions=[];m.targetBindings=[];m.boundViews=[];b.viewModel!=null?m.viewModel=b.viewModel:(m.viewModel={},m.viewModel.id="[None]");m.parentView=b.parentView?b.parentView:b;if(n.startsWith("@"))if(n.startsWith("@event-")){var o=n.split("-")[1];o?(m.type="event",m.attributeName=o):(this.app.trace.warning("Binding error: Invalid event binding expression '{0}' in view '{1}'.".format(n,b.id)),i=true)}else if(n.startsWith("@var"))m.type="var";else if(n.startsWith("@text"))m.attributeName=
"innerHTML",m.type="text";else if(n.startsWith("@attach"))m.attributeName="___attachedValue",m.type="attachment";else if(n.startsWith("@style-"))h=n.indexOf("-"),(h=n.substring(h+1))?(m.type="style",m.attributeName=h):(this.app.trace.warning("Binding error: Invalid style binding expression '{0}' in view '{1}'.".format(n,b.id)),i=true);else if(n.startsWith("@dom"))m.type="dom",m.attributeName=o;else if(n.startsWith("@value"))m.type="value",m.attributeName=o;else if(n==="@source"){m.type="source";m.attributeName=
"@source";g=true;m.templateMode="single-inline";for(n=0;n<j.length;++n)if(o=j[n],o!==h)if(l=o.directive,o=o.target,l==="@template"){m.templateMode="single-external";var p=b.app.viewManager.createView({markup:o,libraryId:b.libraryId});if(!p){b.app.trace.error("Could not instantiate template '{0}' while binding view '{1}'.".format(templateName,this.id));break}p.app=b.app;m.templateSelections={"@default":p.root};break}else if(l==="@template-selector"){m.templateMode="inline-selected";m.templateKey=o;
m.templateSelections={};break}if(m.templateMode!=="single-external"){h=new dojo.NodeList;for(n=0;n<k.children.length;++n)for(var l=k.children[n],o=dojo.attr(l,"data-binding"),p=f(o),r=0;r<p.length;++r)if(o=p[r],o.directive==="@template-for"||o.directive==="@template-select"){if(o.directive==="@template-for"&&o.target===m.target)h.push(l),p=dojo.clone(l),m.templateSelections["@default"]=p,p.___domParent=k;else if(o.directive==="@template-select"){h.push(l);for(var r=false,w=0;w<p.length;++w){var x=
p[w];if(x.directive==="@template"){p=b.app.viewManager.createView({markup:x.target,libraryId:b.libraryId});if(!p){this.app.trace.error("Could not instantiate template '{0}' while binding view '{1}'.".format(templateName,this.id));break}p.app=b.app;r=dojo.clone(l);dojo.place(p.root,r,"last");m.templateSelections[o.target]=r;r=true;break}}if(!r)h.push(l),m.templateSelections[o.target]=l,l.___domParent=k}break}h.orphan()}}else if(n==="@source-remove")m.type="source-remove",m.attributeName=o;else if(n===
"@source-add")m.type="source-add",m.attributeName=o;else if(n==="@visible"||n==="@hidden"){if(n==="@hidden")m.invert=true;m.type="visibility";m.attributeName="@visibility"}else n.startsWith("@template")?m.type="template":n.startsWith("@halt")?g=true:(b.app.trace.warning("Unknown binding term '{0}'.".format(n)),i=true);else m.type="attr",m.attributeName=n;i||b.applyBinding.apply(b,[k,m,e,c])&&a.push(m)})();h=new geocortex.framework.ui.BindingNode;h.domElement=k;h.parent=c;h.context=c.context;h.children=
[];h.expressions=[];c.children.push(h);g==false&&!l&&a(h,k)}}else l||a(c,k)}}var b=this;if(this.root!=null){var c=new geocortex.framework.ui.BindingNode;c.domElement=null;c.parent=null;c.children=[];c.context=this.viewModel;a(c,this.root);return c}},getBindingTarget:function(a){if(a.target==="@context")return a.viewModel;if(a.target.indexOf("@language-")>-1)return this.app.getResource(this.libraryId,"language-"+a.target.split("-").slice(1).join("-"));if(a.viewModel.isObservable!=true)return a.viewModel[a.target];
else{var b=a.viewModel.get();return b==null?b:b[a.target]}},setBindingTargetValue:function(a,b){if(a.target==="@context")a.viewModel!=null&&a.viewModel.isObservable?a.viewModel.set(b):a.viewModel=b;else if(!(a.target.indexOf("@language-")>-1))if(a.viewModel.isObservable!=true)a.viewModel[a.target].isObservable?a.viewModel[a.target].set(b):a.viewModel[a.target]=b;else{var c=a.viewModel.get();c!=null&&(c[target]?c[target].isObservable?c[target].set(b):c[target]=b:c[target]=new Observable(b))}},resolveBindingTemplate:function(a,
b){var c=null;if(a.templateMode==="single-inline"||a.templateMode==="single-external")c=dojo.clone(a.templateSelections["@default"]);else if(a.templateMode==="inline-selected"){var d=null;b[a.templateKey]&&(d=b[a.templateKey],d.isObservable&&(d=d.get()));d?a.templateSelections.hasOwnProperty(d)&&(c=dojo.clone(a.templateSelections[d])):a.templateSelections.hasOwnProperty("@null")&&(c=dojo.clone(a.templateSelections["@null"]));!c&&a.templateSelections.hasOwnProperty("@default")&&(c=dojo.clone(a.templateSelections["@default"]))}c||
(c=dojo.create("div"));return c},buildSourceBinding:function(a,b,c,d){var e=this,f=e.getBindingTarget(b);if(f===null)return false;if(f===void 0||!f.bind)return e.app.trace.warning("Binding error: '{0}' in view model '{1}' was not bindable.".format(b.target,b.viewModel.id)),false;var i=function(c){for(var i=null,h=null,j=0;j<d.expressions.length;++j){var g=d.expressions[j];if(i==null&&g.type=="source-add")i=g.target;if(h==null&&g.type=="source-remove")h=g.target}j=this;if(b.parentView)j=b.parentView;
var q=j[i],i=j[h];if(c.declaredClass!="geocortex.framework.events.CollectionChangedArgs"){h=c.isObservable?c.get():c;i&&i.apply(e,[b,h,c,0]);for(g=0;g<b.boundViews.length;++g)this.app.viewManager.destroyView(b.boundViews[g]);b.boundViews=[];if(!i&&(g=b.___singleSourceItem))j=new dojo.NodeList,j.push(g),j.orphan(),b.___singleSourceItem=null;if(h)if(q)q.apply(e,[b,h,c,0]);else{j=e.resolveBindingTemplate(b,h);dojo.place(j,b.domElement,"last");g=new geocortex.framework.ui.ViewBase;g.parentView=b.parentView;
g.app=g.parentView.app;g.libraryId=e.libraryId;var s={children:[]};s.children.push(j);if(h===null||h===void 0)h=new geocortex.framework.ui.ViewModelBase,h.app=e.app,h.libraryId=e.libraryId;h.hasOwnProperty("___boundViews");g.root=s;g.attach(h);g.root=j;b.___singleSourceItem=g.root;b.boundViews.push(g)}}else if(c===null||c.type=="clear"){if(i)for(g=c.rangeStart;g<=c.rangeEnd;++g)i.apply(e,[b,f.getAt(g),c,g]);for(g=0;g<b.boundViews.length;++g)this.app.viewManager.destroyView(b.boundViews[g]);b.boundViews=
[];if(!i&&b.domElement!=null&&b.domElement.children!=null){j=new dojo.NodeList;for(g=0;g<b.domElement.children.length;++g)b.domElement.children[g].___collectionTemplate||j.push(b.domElement.children[g]);j.orphan()}}else if(c.type=="replace"){if(i)for(g=c.rangeStart;g<c.rangeEnd+1;++g)i.apply(e,[b,f.getAt(g),c,g]);for(g=0;g<b.boundViews.length;++g)this.app.viewManager.destroyView(b.boundViews[g]);b.boundViews=[];i||dojo.empty(b.domElement);c.type="append";c.rangeStart=0;c.rangeEnd=f.value.length-1}if(c.type==
"append"||c.type=="insert"){var t=null;c.type=="insert"&&b.domElement.children.length>c.rangeStart&&(t=b.domElement.children[c.rangeStart]);var u=function(d,i){if(d>i)return false;for(var h=d;h<=i;++h){var g=null;if(q!=null)q.apply(e,[b,f.getAt(h),c,h]);else{var n=f.getAt(h),g=e.resolveBindingTemplate(b,n);t&&c.type=="insert"?dojo.place(g,t,"before"):t&&c.type=="append"?dojo.place(g,t,"after"):dojo.place(g,b.domElement,"last");var j=new geocortex.framework.ui.ViewBase;j.parentView=b.parentView;j.app=
j.parentView.app;j.libraryId=e.libraryId;j.id+="-item"+h;var l={children:[]};l.children.push(g);if(n===null||n===void 0)n=new geocortex.framework.ui.ViewModelBase,n.app=e.app,n.libraryId=e.libraryId;n.hasOwnProperty("___boundViews");j.root=l;j.attach(n);j.root=g;b.boundViews.push(j)}}a.___populateInitialValueFunc&&(a.___populateInitialValueFunc(),Array.removeItem(a,a.___populateInitialValueFunc));return true};if(f.useThrottling){var v=c.rangeStart,n=Math.min(v+10,c.rangeEnd);new geocortex.framework.utils.ThrottledOperation(f.throttleDelay,
function(){if(n>c.rangeEnd)return false;var a=u(v,n);v+=10;n+=10;return a})}else u(c.rangeStart,c.rangeEnd)}else if(c.type=="remove")for(h=c.rangeStart;h<=c.rangeEnd;++h)for(j=0;j<b.boundViews.length;++j)g=b.boundViews[j],g.viewModel&&g.viewModel===f.getAt(h)&&(i?i.apply(e,[b,object,c,h]):e.app.viewManager.destroyView(g),Array.removeItem(b.boundViews,g),--j)};b.targetBindings.push({event:f.bindingEvent,token:f.bind(e,i)});if(this.pulses==null)this.pulses=[];f.isObservableCollection?this._bindingSetupDelegates.push(function(){var a=
new geocortex.framework.events.CollectionChangedArgs;a.type="append";a.rangeStart=0;a.rangeEnd=f.getLength()-1;a.sender=f;i.apply(e,[a])}):this._bindingSetupDelegates.push(function(){i.apply(e,[f])})},buildEventBinding:function(a,b,c){var d=this;if(b.parentView)d=b.parentView;if(d[b.target])b.domEventSubscriptions.push(dojo.connect(a,b.attributeName,null,function(e){var f=d[b.target](e,a,c);return!f?(dojo.stopEvent(e),false):f}));else return this.app.trace.warning("Binding error: Event handler '{0}' was not found in view '{1}'.".format(b.target,
d.id)),false},buildVarBinding:function(a,b){var c=this;if(b.parentView)c=b.parentView;var d=c[b.target];d?d&&d instanceof Array?d.push(a):d&&d.isObservableCollection?d.addItem(d):c[b.target]=a:c[b.target]=a},buildTextBinding:function(a,b){var c=this.getBindingTarget(b);if(c===null)return false;if(c===void 0)return this.app.trace.warning("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;else if(c!=null&&!c.isObservable)b.attributeName==="innerHTML"?
(dojo.empty(a),a.appendChild(document.createTextNode(c))):dojo.attr(a,b.attributeName,String.escapeHtml(c));else{var d=c.get(),d=d===null||d===void 0?"":d.toString();c!=null&&b.targetBindings.push({event:c.bindingEvent,token:c.bind(this,function(c){b.attributeName==="innerHTML"?(dojo.empty(a),a.appendChild(dojo.doc.createTextNode(c))):dojo.attr(a,b.attributeName,String.escapeHtml(c))})});b.attributeName==="innerHTML"?(dojo.empty(a),a.appendChild(dojo.doc.createTextNode(d))):dojo.attr(a,b.attributeName,
String.escapeHtml(d))}},buildAttributeBinding:function(a,b,c,d){var e=this.getBindingTarget(b);if(e===null)return false;if(e===void 0)return this.app.trace.warning("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;else if(e!=null&&!e.isObservable){if(e===null||e===void 0)e="";d===true?a[b.attributeName]=e:dojo.attr(a,b.attributeName,e)}else if(e!=null){b.targetBindings.push({event:e.bindingEvent,token:e.bind(this,function(){var c=e.get();if(c===
null||c===void 0)c="";d===true?a[b.attributeName]=c:dojo.attr(a,b.attributeName,c)})});c=e.get();if(c===null||c===void 0)c="";dojo.attr(a,b.attributeName,c)}},buildStyleBinding:function(a,b){var c=this,d=this.getBindingTarget(b);if(d==null)return false;if(d===void 0)return this.app.trace.warning("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;else if(d!=null&&!d.isObservable){var e=!isNaN(d)?d+"px":d;dojo.style(a,b.attributeName,e)}else if(d!=
null){var f=function(){var c;c=d.get();c=!isNaN(c)?c+"px":c;dojo.style(a,b.attributeName,c)};b.targetBindings.push({event:d.bindingEvent,token:d.bind(this,f)});this._bindingSetupDelegates.push(function(){f.apply(c,[null])})}},buildDomBinding:function(a,b){var c=this;if(b.parentView)c=b.parentView;var d=c[b.target];if(d==null)return false;if(d===void 0)return this.app.trace.warning("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;else try{if(d.isObservable==
true){b.targetBindings.push({event:d.bindingEvent,token:d.bind(this,function(){if(!d.get())return false;b.domElement=dojo.place(d.get(),b.domElement,"replace");this.app&&this.app.viewManager.notifyDimensionsChanged(this)})});if(!d.get())return false;dojo.place(d.get(),b.domElement,"replace")}else{if(!d)return false;dojo.place(d,b.domElement,"replace")}}catch(e){this.app.trace.warning("Binding error: An error occurred in view '{0}' while attempting to perform a DOM binding in view model '{1}'.".format(this.id,
b.viewModel.id))}},buildVisibilityBinding:function(a,b){var c=this.getBindingTarget(b);if(c===void 0)return this.app.trace.debug("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;else{b.initialVisibility=dojo.style(a,"display")||"block";var d=function(d){var e=false;if(d){if(c)if(d.declaredClass=="geocortex.framework.events.CollectionChangedArgs")if(d.type=="append"){if(d.rangeEnd+1-d.rangeStart>0||c.value&&c.value.length>0)e=true}else d.type==
"clear"?e=false:d.type=="insert"?d.rangeEnd+1-d.rangeStart>0&&(e=true):d.type=="remove"&&d.rangeEnd+1-d.rangeStart<c.value.length&&(e=true);else e=c.isObservableCollection?c.getLength()>0:c.isObservable?!!c.get():d===true?true:typeof d==="string"?d.length>0:false}else e=false;b.invert==true&&(e=!e);d="";d=b.initialVisibility==="inline"?"bound-visible-inline":"bound-visible";e==true?(dojo.removeClass(a,"bound-invisible"),dojo.addClass(a,d)):(dojo.removeClass(a,d),dojo.addClass(a,"bound-invisible"))},
e=this;b.targetBindings.push({event:c.bindingEvent,token:c.bind(this,d)});this._bindingSetupDelegates.push(function(){d.apply(e,[c])})}},buildValueBinding:function(a,b){var c=this,d=this.getBindingTarget(b);if(d==null)return false;if(d===void 0)return this.app.trace.warning("Binding error: Property '{0}' does not exist in view model '{1}'.".format(b.target,b.viewModel.id)),false;var e=d.isObservable||false,f=d.isObservableCollection||false,i=a.tagName.toLowerCase(),k=dojo.attr(a,"type");if(e){var l=
function(b){if(b===null||b===void 0)b="";dojo.attr(a,"value",b)},h=function(b){a.checked=b===true},j=function(b){var c=dojo.attr(a,"value");dojo.query("input[type=radio]",this.root).forEach(function(){});a.checked=b===true||c==b?true:false},g=function(a){if(a===null||a===void 0)for(var c=0;c<b.domElement.options.length;++c){var d=b.domElement.options[c];d.selected=false}else if(a.isObservableCollection){if(dojo.attr(b.domElement,"multiple"))if(b.viewModel[b.target].isObservableCollection)for(c=0;c<
b.domElement.options.length;++c){d=b.domElement.options[c];d.selected=false;for(var e=0;e<a.length;++e)if(a[e]===d.value){d.selected=true;break}}else for(c=0;c<b.domElement.options.length;++c)if(d=b.domElement.options[c],d.value==a){d.selected=true;break}}else for(c=0;c<b.domElement.options.length;++c)if(d=b.domElement.options[c],d.value==a){d.selected=true;break}};i==="select"?(b.targetBindings.push({event:d.bindingEvent,token:d.bind(b,g)}),c._bindingSetupDelegates.push(function(){g.apply(c,[d.get()])})):
k==="radio"?(b.targetBindings.push({event:d.bindingEvent,token:d.bind(b,j)}),c._bindingSetupDelegates.push(function(){j.apply(c,[d.get()])})):k==="checkbox"?(b.targetBindings.push({event:d.bindingEvent,token:d.bind(b,h)}),c._bindingSetupDelegates.push(function(){h.apply(c,[d.get()])})):(b.targetBindings.push({event:d.bindingEvent,token:d.bind(b,l)}),c._bindingSetupDelegates.push(function(){l.apply(c,[d.get()])}))}var q=function(a){b.domEventSubscriptions.push(dojo.connect(a,"change",function(a){a=
dojo.attr(a.currentTarget,"value");e?d.set(a):c.setBindingTargetValue(b,a);return true}))},s=function(a){b.domEventSubscriptions.push(dojo.connect(a,"change",function(a){a=dojo.attr(a.currentTarget,"checked");e?d.set(a):c.setBindingTargetValue(b,a);return true}))},t=function(a){b.domEventSubscriptions.push(dojo.connect(a,"click",function(a){dojo.attr(a.currentTarget,"checked")&&(e?d.set(a.currentTarget.value):c.setBindingTargetValue(b,a.currentTarget.value));return true}))},u=function(a){a.___populateInitialValueFunc=
function(){g(d.isObservable?d.get():d)};b.domEventSubscriptions.push(dojo.connect(a,"change",function(){for(var h=dojo.query("option",a),g=[],i=0;i<h.length;++i){var j=h[i];if(j.selected===true){var k=j.___attachedValue;k?g.push(k):g.push(j.value)}}if(g.length===0&&h.length>0&&!a.multiple&&c.app.___uaIsiPad===true)a.selectedIndex=0,k=h[0].___attachedValue,g.push(k?k:h[0].value);g.length>0?f?(d.clear(),d.addItems(g)):e?d.set(g[0]):c.setBindingTargetValue(b,g):d.clear();return true}))};i==="textarea"||
i==="input"&&k==="text"?function(a){var f=null,g=function(a){a=dojo.attr(a.currentTarget,"value");if(a!==f)return f=a,e?d.set(a):c.setBindingTargetValue(b,a),true};b.domEventSubscriptions.push(dojo.connect(a,"change",g));b.domEventSubscriptions.push(dojo.connect(a,"keyup",g));b.domEventSubscriptions.push(dojo.connect(a,"mouseup",g))}(a):i==="input"&&k==="checkbox"?s(a):i==="input"&&k==="radio"?t(a):i==="select"?u(a):q(a)},applyBinding:function(a,b,c,d){b.type==="source"?this.buildSourceBinding(a,
b,c,d):b.type==="event"?this.buildEventBinding(a,b,c):b.type==="text"?this.buildTextBinding(a,b,c):b.type==="var"?this.buildVarBinding(a,b,c):b.type==="style"?this.buildStyleBinding(a,b,c):b.type==="dom"?this.buildDomBinding(a,b,c):b.type==="value"?this.buildValueBinding(a,b,c):b.type==="attr"?this.buildAttributeBinding(a,b,c):b.type==="attachment"?this.buildAttributeBinding(a,b,c,true):b.type==="visibility"&&this.buildVisibilityBinding(a,b,c);return true},getResource:function(a,b){return this.app.getResource(this.libraryId,
a,b)}});
dojo.declare("geocortex.framework.ui.ViewManager",null,{constructor:function(a){this.app=a;this._views=[];this._hostedRegions=[];this._pendingRegions=[];this._registerCommands()},app:null,_views:null,_hostedRegions:null,_pendingRegions:null,shutdown:function(){for(var a=0;a<this._hostedRegions.length;++a)this.destroyRegion(this._hostedRegions[a]);this._hostedRegions=[];for(var b=0;b<this._views.length;++b)this.destroyView(this._views[b]);this._views=[];for(a=0;a<this._pendingRegions.length;++a){for(var c=this._pendingRegions[a],
b=0;b<c.views.length;++b)this.destroyView(c.views[b]);c.views=[]}this._pendingRegions=[]},_registerCommands:function(){this.app.commandRegistry.command("ActivateView").register(this,function(a){var b=this.getViewById(a);b?this.activateView(b):this.app.trace.warning("ActivateView: Could not find view '{0}'.".format(a))});this.app.commandRegistry.command("DeactivateView").register(this,function(a){var b=this.getViewById(a);b?this.deactivateView(b):this.app.trace.warning("DeactivateView: Could not find view '{0}'.".format(a))});
this.app.commandRegistry.command("ToggleView").register(this,function(a){var b=this.getViewById(a);b?this.toggleView(b):this.app.trace.warning("ToggleView: Could not find view '{0}'.".format(a))});this.app.commandRegistry.command("DestroyView").register(this,function(a){var b=this.getViewById(a);b?this.destroyView(b):this.app.trace.warning("DestroyView: Could not find view '{0}'.".format(a))})},activateView:function(a){if(!a.id)return this.app.trace.error("ViewManager: Invalid or nonexistent view passed to activateView."),
false;var b=this.getRegionForViewId(a.id);if(!b){if(!a.regionName)return this.app.trace.warning("Could not activate view '{0}' - view is not associated with a region.".format(a.id)),false;if(b=this.getExistingRegionByName(a.regionName))return b.hostView(a),b.activateView(a),true;else(b=this._getPendingRegionEntryByName(a.regionName))?Array.contains(b.views,a)?this.app.trace.debug("View '{0}' re-added to pending region '{1}'.".format(a.id,a.regionName)):b.views.push(a):(b={},b.name=a.regionName,b.views=
[],b.views.push(a),this._pendingRegions.push(b));return false}b.activateView(a);return true},deactivateView:function(a){if(!a.id)return this.app.trace.error("ViewManager: Invalid or nonexistent view passed to deactivateView."),false;var b=this.getRegionForViewId(a.id);if(!b)return this.app.trace.debug("Could not find region for view '{0}'.".format(a.id)),false;b.deactivateView(a);return true},toggleView:function(a){a.isActive?this.deactivateView(a):this.activateView(a)},createView:function(a){var b=
a.viewId||a.id;if(b&&this.getViewById(b))this.app.trace.error("Could not create view '{0}' - a view with that ID already exists.".format(b));else{var c=a.typeName||a.type||"geocortex.framework.ui.ViewBase",d=null,e=null;try{d=dojo.getObject(c,true),e=new d(this.app),e.app=this.app}catch(f){return this.app.trace.error("Could not instantiate view with type '{0}' - type was not found or view constructor failed.".format(a.typeName)),null}c=a.isVisible||a.visible;e.id=b==null?"View-"+geocortex.utils.alphaNumericToken():
b;e.markupResource=a.markupResource||a.markup;e.regionName=a.regionName||a.region;e.configuration=a.configuration||a.config||{};e.isManaged=a.isManaged||false;e.title.set(a.title||"");e.description.set(a.description);e.iconUri.set(a.iconUri);e.libraryId=a.libraryId;if(e.regionName)(a=this.getExistingRegionByName(e.regionName))?(this._views.push(e),a.hostView(e),c&&a.activateView(e)):(c&&(e.___shouldActivate=true),(a=this._getPendingRegionEntryByName(e.regionName))?Array.contains(a.views,e)?this.app.trace.debug("View '{0}' re-added to pending region '{1}'.".format(e.id,
e.regionName)):a.views.push(e):(a={},a.name=e.regionName,a.views=[],a.views.push(e),this._pendingRegions.push(a)));else{a=geocortex.resourceManager.fetch(e.markupResource,e.libraryId);if(a==null)return this.app.trace.warning("Could not fetch markup resource '{0}'.".format(e.markupResource)),null;else e.root=dojo.create("div"),e.root.innerHTML=a;this._views.push(e)}return e}},create:function(a,b,c,d,e){var f=new geocortex.framework.config.ViewConfig;f.typeName=a;f.markupResource=c;f.isActive=true;
f.regionName=d;f.configuration={};a=this.createView(f,e);if(a===null)return a;b=dojo.getObject(b||"geocortex.framework.ui.ViewModelBase",true);c=null;try{c=new b(this.app),c.app=this.app,c.libraryId=e,c.initialize({})}catch(i){return this.trace.error("Could not create view model with type '{0}' - type was not found, not a view model, or failed to construct: {1}".format(viewModelConfig.typeName,i.message)),null}a.attach(c);this.activateView(a);return a},destroyView:function(a){var b=this.getRegionForViewId(a.id);
b!=null&&(b.deactivateView(a),b.unhostView(a));a.destroyBindings();if(a.childRegions!=null)for(b=0;b<a.childRegions.length;++b)this.destroyRegion(a.childRegions[b]);a.root!=null&&(b=new dojo.NodeList,b.push(a.root),b.orphan());Array.removeItem(this._views,a)},destroyRegion:function(a){if(a.views!=null)for(var b=0;b<a.views.length;++b)this.destroyView(a.views[b]);a.unhost()},discoverRegions:function(a,b){var c=this;a!=null&&dojo.query("[data-region-name]",a).forEach(function(a){var e=dojo.attr(a,"data-region-name");
if(c.getExistingRegionByName(e))c.app.trace.error("Region '{0}' already exists.".format(e));else{var f=c._getPendingRegionEntryByName(e),i=null;f&&c._removePendingRegionEntry(e);var k=dojo.attr(a,"data-region-adapter"),l=null;try{k||(k="geocortex.framework.ui.DivRegionAdapter"),l=dojo.getObject(k,true),i=new l(e,c.app)}catch(h){return c.app.trace.error("Could not instantiate region with type '{0}' - type was not found.".format(k)),null}i.host(a);c._hostedRegions.push(i);b!=null&&b.childRegions.push(i);
if(f)for(a=0;a<f.views.length;++a)e=f.views[a],c._views.push(e),i.hostView(e),e.___shouldActivate&&(Array.removeItem(e,e.___shouldActivate),i.activateView(e))}})},getExistingRegionByName:function(a){for(var b=0;b<this._hostedRegions.length;++b){var c=this._hostedRegions[b];if(c.name==a)return c}return null},_getPendingRegionEntryByName:function(a){for(var b=0;b<this._pendingRegions.length;++b){var c=this._pendingRegions[b];if(c.name==a)return c}return null},_removePendingRegionEntry:function(a){for(var b=
-1,c=0;c<this._pendingRegions.length;++c)if(this._pendingRegions[c].name==a){b=c;break}return c>-1?(Array.remove(this._pendingRegions,b),true):false},getRegionForViewId:function(a){for(var b=0;b<this._hostedRegions.length;++b)for(var c=this._hostedRegions[b],d=0;d<c.views.length;++d)if(c.views[d].id===a)return c;return null},getViewById:function(a){for(var b=0;b<this._views.length;++b){var c=this._views[b];if(c.id&&c.id==a)return c}},notifyDimensionsChanged:function(a){if(a&&a.id){var b=this.getRegionForViewId(a.id),
a=new geocortex.framework.events.ViewDimensionsChangedArgs(a,b);this.app.eventRegistry.event("ViewDimensionsChangedEvent").publish(a)}}});dojo.declare("geocortex.framework.ui.ViewModelBase",null,{constructor:function(a){this.app=a;this.id="ViewModel-"+geocortex.utils.alphaNumericToken()},app:null,id:null,libraryId:null,initialize:function(){},getResource:function(a,b){return this.app.getResource(this.libraryId,a,b)}});
Array.remove=function(a,b,c){c=a.slice((c||b)+1||a.length);a.length=b<0?a.length+b:b;return a.push.apply(a,c)};Array.removeItem=function(a,b){var c=Array.pos(a,b);if(c==-1)return false;else Array.remove(a,c,c)};Array.contains=function(a,b){for(var c=a.length;c--;)if(a[c]===b)return true;return false};Array.pos=function(a,b){for(var c=a.length;c--;)if(a[c]===b)return c;return-1};
String.prototype.format=function(a){for(var a=Array.prototype.slice.call(arguments),b=this,c=0;c<a.length;c++)b=b.replace(RegExp("\\{"+c+"\\}","gi"),a[c]);return b};String.format=function(a){var b=Array.prototype.slice.call(arguments);return a.format(b.slice(1))};String.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")};String.isNullOrEmpty=function(a){return a==null||a.length==0};
String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.ltrim=function(){return this.replace(/^\s+/,"")};String.prototype.rtrim=function(){return this.replace(/\s+$/,"")};String.prototype.startsWith=function(a){return this.indexOf(a)==0};dojo.provide("geocortex.framework.utils.ThrottledOperation");
dojo.declare("geocortex.framework.utils.ThrottledOperation",null,{period:null,action:null,constructor:function(a,b){this.period=a;this.action=b;var c=this;setTimeout(function(){c.execute(c)},this.period)},execute:function(a){a.action()&&setTimeout(function(){a.execute(a)},this.period)}});
dojo.declare("geocortex.framework.utils.TimeDelayedAction",null,{delayMS:null,func:null,_timer:null,constructor:function(a,b,c){this.delayMS=a;this.func=c?dojo.hitch(c,b):b},start:function(){this._timer=setTimeout(this.func,this.delayMS)},stop:function(){clearTimeout(this._timer)},reset:function(){this.stop();this.start()}});
dojo.declare("geocortex.framework.utils.Trace",null,{constructor:function(a){this.app=a},app:null,_debugElement:null,_logEvent:null,_traceImpl:function(a,b){(a!="debug"||this.app.debugMode)&&this.app.eventRegistry.event("TraceEvent").publish({level:a,timestamp:new Date,message:b})},debug:function(a){this._traceImpl("debug",a)},trace:function(a){this._traceImpl("trace",a)},info:function(a){this._traceImpl("info",a)},alert:function(a){this._traceImpl("alert",a)},warning:function(a){this._traceImpl("warning",
a)},error:function(a){this._traceImpl("error",a)},exception:function(a){this._traceImpl("error",a)}});if(geocortex.framework!=null&&geocortex.framework.utils==null)geocortex.framework.utils={};geocortex.framework.utils.base64keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
geocortex.framework.utils.alphaNumericToken=function(a){for(var a=a||8,b="",c=0;c<a;c++){var d=Math.floor(Math.random()*61);b+="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz".substring(d,d+1)}return b};
geocortex.framework.utils.base64Encode=function(a){for(var b="",c,d,e,f,i,k,l=0,a=this.utf8Encode(a);l<a.length;)c=a.charCodeAt(l++),d=a.charCodeAt(l++),e=a.charCodeAt(l++),f=c>>2,c=(c&3)<<4|d>>4,i=(d&15)<<2|e>>6,k=e&63,isNaN(d)?i=k=64:isNaN(e)&&(k=64),b=b+this.base64keyStr.charAt(f)+this.base64keyStr.charAt(c)+this.base64keyStr.charAt(i)+this.base64keyStr.charAt(k);return b};
geocortex.framework.utils.base64Decode=function(a){var b="";if(!a||a=="")return b;var c,d,e="",f,i="",k=0;if(/[^A-Za-z0-9\+\/\=]/g.exec(a))throw Error("There were invalid base64 characters in the input text.\nValid base64 characters are A-Z, a-z, 0-9, '+', '/',and '='\nExpect errors in decoding.");a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do c=this.base64keyStr.indexOf(a.charAt(k++)),d=this.base64keyStr.indexOf(a.charAt(k++)),f=this.base64keyStr.indexOf(a.charAt(k++)),i=this.base64keyStr.indexOf(a.charAt(k++)),
c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|i,b+=String.fromCharCode(c),f!=64&&(b+=String.fromCharCode(d)),i!=64&&(b+=String.fromCharCode(e));while(k<a.length);return unescape(b)};geocortex.framework.utils.utf8Encode=function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);d<128?b+=String.fromCharCode(d):(d>127&&d<2048?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b};
if(geocortex==null)var geocortex={};if(geocortex.framework==null)geocortex.framework={},geocortex.framework.initialized=false;dojo.safeMixin(geocortex.framework,{applications:[],libraries:{}});geocortex.framework.registerApplication=function(a){geocortex.framework.applications.push(a)};geocortex.framework.notifyLibraryDownload=function(a){for(var b=0;b<geocortex.framework.applications.length;++b){var c=geocortex.framework.applications[b];geocortex.framework.libraries[a]=true;c.notifyLibraryDownload(a)}};
geocortex.framework.hasLibrary=function(a){return geocortex.framework.libraries.hasOwnProperty(a)};var resourceManager=ObservableCollection=Observable=null;
geocortex.framework.initialize=function(){if(!geocortex.framework.initialized)geocortex.resourceManager=new geocortex.framework.application.ResourceManager,geocortex.utils=geocortex.framework.utils,Observable=dojo.getObject("geocortex.framework.events.Observable"),ObservableCollection=dojo.getObject("geocortex.framework.events.ObservableCollection"),geocortex.framework.initialized=true};geocortex.framework.initialize();
